name: Gosec Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gosec_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17' # Adjust the Go version as needed

      - name: Install gosec via snap
        run: |
          sudo snap install gosec

      - name: Run gosec
        run: gosec -exclude=G104 ./...
