name: Secrets Scanner

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  secrets_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install gitleaks
        run: |
          curl -sSfL \
          https://install.goreleaser.com/github.com/zricethezav/gitleaks.sh | sh


      - name: Run Secrets Scanner
        run: |
          gitleaks --path=. --report=gitleaks-report.txt

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: gitleaks-report
          path: gitleaks-report.txt
