name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install SonarCloud Scanner
        run: |
          curl -sLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.2.21-linux.zip
          unzip -o sonar-scanner-cli.zip
          export PATH="$PWD/sonar-scanner-4.7.2.21-linux/bin:$PATH"
          chmod +x sonar-scanner-4.7.2.21-linux/bin/sonar-scanner

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: "<Your SonarCloud organization>"
          SONAR_PROJECT_KEY: "<Your SonarCloud project key>"
        run: sonar-scanner

